# Generated by Django 3.1 on 2020-10-12 01:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft_round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_round', models.CharField(choices=[('ー', 'ー'), ('１位', '１位'), ('２位', '２位'), ('３位', '３位'), ('４位', '４位'), ('５位', '５位'), ('６位', '６位'), ('７位', '７位'), ('８位', '８位'), ('９位', '９位'), ('育成１位', '育成１位'), ('育成２位', '育成２位'), ('育成３位', '育成３位'), ('育成４位', '育成４位'), ('育成５位', '育成５位'), ('育成６位', '育成６位'), ('育成７位', '育成７位'), ('育成８位', '育成８位'), ('育成９位', '育成９位')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch_and_Bat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_and_bad', models.CharField(choices=[('右投げ右打ち', '右投げ右打ち'), ('右投げ左打ち', '右投げ左打ち'), ('右投げ両打ち', '右投げ両打ち'), ('左投げ右打ち', '左投げ右打ち'), ('左投げ左打ち', '左投げ左打ち'), ('左投げ両打ち', '左投げ両打ち')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('投手', '投手'), ('捕手', '捕手'), ('内野手', '内野手'), ('外野手', '外野手')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('巨人', '巨人'), ('DeNA', 'DeNA'), ('阪神', '阪神'), ('広島', '広島'), ('中日', '中日'), ('ヤクルト', 'ヤクルト'), ('西武', '西武'), ('ソフトバンク', 'ソフトバンク'), ('楽天', '楽天'), ('ロッテ', 'ロッテ'), ('日本ハム', '日本ハム'), ('オリックス', 'オリックス')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='選手名')),
                ('uniform_number', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[0-9]*$', '数字のみです')], verbose_name='背番号')),
                ('birthday', models.DateField(verbose_name='生年月日')),
                ('height', models.IntegerField(default=170, validators=[django.core.validators.MinValueValidator(160)], verbose_name='身長')),
                ('weight', models.IntegerField(default=70, verbose_name='体重')),
                ('professional_years', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='プロ通算年数')),
                ('cheering_song', models.TextField(blank=True, max_length=80, verbose_name='選手応援歌')),
                ('coment', models.TextField(blank=True, max_length=100, verbose_name='選手紹介')),
                ('draft_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.draft_round', verbose_name='ドラフト順位')),
                ('pitch_and_bat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.pitch_and_bat', verbose_name='投打')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.position', verbose_name='守備位置')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.team', verbose_name='チーム')),
            ],
        ),
    ]
