# Generated by Django 3.1 on 2020-10-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft_round',
            name='draft_round',
            field=models.CharField(choices=[('-', '-'), ('１位', '１位'), ('２位', '２位'), ('３位', '３位'), ('４位', '４位'), ('５位', '５位'), ('６位', '６位'), ('７位', '７位'), ('８位', '８位'), ('９位', '９位'), ('育成１位', '育成１位'), ('育成２位', '育成２位'), ('育成３位', '育成３位'), ('育成４位', '育成４位'), ('育成５位', '育成５位'), ('育成６位', '育成６位'), ('育成７位', '育成７位'), ('育成８位', '育成８位'), ('育成９位', '育成９位')], max_length=4),
        ),
    ]
